version: '3'
services:
  # Main proxy container
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf

  # Letsencrypt companion container
  acme-companion:
    image: nginxproxy/acme-companion:${ACME_COMPANION_VERSION}
    container_name: acme-companion
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/acme:/etc/acme.sh"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf
    environment: 
      DEFAULT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
    depends_on:
      - nginx-proxy

  # Postgres DB container
  postgresdb:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresdb
    restart: always
    volumes:
      - "${DATA_DIR}/postgresql:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}

  # PGAdmin container
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin
    restart: always
    user: root
    volumes:
      - "${DATA_DIR}/pgadmin:/var/lib/pgadmin:rw"
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: "yes"
      VIRTUAL_HOST: ${PGADMIN_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${PGADMIN_SUBDOMAIN}.${ROOT_HOST}
    depends_on:
      - postgresdb

  # MariaDB container
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    restart: always
    volumes:
      - "${DATA_DIR}/mariadb:/var/lib/mysql"
    environment: 
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  # PHPMyAdmin container
  myadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: myadmin
    restart: always
    volumes:
      - "${DATA_DIR}/postgresql:/var/lib/postgresql/data"
    links:
      - mariadb
    environment: 
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PHPMYADMIN_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${PHPMYADMIN_SUBDOMAIN}.${ROOT_HOST}
    depends_on:
      - mariadb

  # InfluxDB container
  influxdb:
    image: influxdb:${INFLUXDB_DB_VERSION}
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB_NAME}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    volumes:
      - "${DATA_DIR}/influxdb:/var/lib/influxdb2"

# Root container
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    restart: always
    volumes:
      - "./dashboard:/usr/share/nginx/html"
    environment:
      VIRTUAL_HOST: ${ROOT_HOST},www.${ROOT_HOST}
      LETSENCRYPT_HOST: ${ROOT_HOST},www.${ROOT_HOST}
    depends_on:
      - acme-companion

      # Bloog container
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    restart: always
    volumes:
      - "${DATA_DIR}/wordpress:/var/www/html/"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_TABLE_PREFIX: "wp_"
      VIRTUAL_HOST: ${WORDPRESS_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${WORDPRESS_SUBDOMAIN}.${ROOT_HOST}
    depends_on:
      - acme-companion
      - mariadb

  # Nextcloud container
  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
    hostname:
      ${NEXTCLOUD_SUBDOMAIN}.${ROOT_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER:  ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_HOST: postgresdb
      VIRTUAL_HOST: ${NEXTCLOUD_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${NEXTCLOUD_SUBDOMAIN}.${ROOT_HOST}
    depends_on:
      - acme-companion
      - postgresdb

  # Grafana container
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    restart: always
    volumes:
      - "${DATA_DIR}/grafana/storage:/var/lib/grafana"
      - "${DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning"
    links:
      - influxdb:influxdb
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${GRAFANA_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${GRAFANA_SUBDOMAIN}.${ROOT_HOST}
      VIRTUAL_PORT: 3000
    depends_on:
      - influxdb
      - acme-companion

  # Plex container
  plex:
    image: linuxserver/plex:${PLEX_VERSION}
    container_name: plex
    restart: always
    volumes:
      - "${DATA_DIR}/plex:/config"
      - "${PLEX_TV_SERIES_DIR}:/tv"
      - "${PLEX_MOVIES_DIR}:/movies"
    hostname:
      ${PLEX_SUBDOMAIN}.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
      VIRTUAL_HOST: ${PLEX_SUBDOMAIN}.${ROOT_HOST}
      LETSENCRYPT_HOST: ${PLEX_SUBDOMAIN}.${ROOT_HOST}
      VIRTUAL_PORT: 32400
    depends_on:
      - acme-companion

