version: '3'
services:
  # Main proxy container
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1-alpine@sha256:8e694857bec619de92f21163a4d15f41fa181cda48af48b4aca0bfd9542b3065
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/htpasswd:/etc/nginx/htpasswd"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf

  # Letsencrypt companion container
  acme-companion:
    image: nginxproxy/acme-companion:2.2.8@sha256:9438ede8e4b8a1b8798c4af4683a04df5fdc0ea0d619fcd38598e4b85f362d02
    container_name: acme-companion
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/acme:/etc/acme.sh"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf
    environment: 
      DEFAULT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
    depends_on:
      - nginx-proxy

  # CAdvisor container
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2@sha256:78cf73632de30193dc249923fdfdb1d43ee7cfccbf64662991de89ff7c4b1fda
    container_name: cadvisor
    restart: unless-stopped
    devices:
      - /dev/kmsg
    hostname: cadvisor
    ipc: shareable
    privileged: true
    command:
      - '-housekeeping_interval=20s'
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  # Node-Exporter container
  node-exporter:
    image: prom/node-exporter:v1.6.1@sha256:81f94e50ea37a88dfee849d0f4acad25b96b397061f59e5095905f6bc5829637
    container_name: node-exporter
    restart: unless-stopped
    hostname: node-exporter

  # BlackBox exporter container
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0@sha256:3af31f8bd1ad2907b4b0f7c485fde3de0a8ee0b498d42fc971f0698885c03acb
    container_name: blackbox-exporter
    restart: unless-stopped
    hostname: blackbox-exporter
    command:
      - '--config.file=/config/blackbox.yml'
    volumes:
      - "./blackbox-exporter:/config"

  # Prometheus container
  prometheus:
    image: prom/prometheus:v2.47.0@sha256:c5dd3503828713c4949ae1bccd1d8d69f382c33d441954674a6b78ebe69c3331
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    hostname: prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
      - "${DATA_DIR}/prometheus/data:/prometheus"
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    depends_on:
      - cadvisor
      - node-exporter
      - blackbox-exporter

# Root container
  nginx:
    image: nginx:1.25.2@sha256:6926dd802f40e5e7257fded83e0d8030039642e4e10c4a98a6478e9c6fe06153
    container_name: nginx
    restart: always
    volumes:
      - "./dashboard:/usr/share/nginx/html"
    environment:
      VIRTUAL_HOST: ${ROOT_HOST},www.${ROOT_HOST}
      LETSENCRYPT_HOST: ${ROOT_HOST},www.${ROOT_HOST}
    depends_on:
      - acme-companion

  # Grafana container
  grafana:
    image: grafana/grafana:10.1.2@sha256:63854c5592bab6c7b8ac2ceb35b420925465eb24ef05f2402e4cb805253efb46
    container_name: grafana
    restart: always
    volumes:
      - "${DATA_DIR}/grafana/storage:/var/lib/grafana"
      - "${DATA_DIR}/grafana/provisioning:/etc/grafana/provisioning"
    links:
      - prometheus:prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      VIRTUAL_HOST: grafana.${ROOT_HOST}
      LETSENCRYPT_HOST: grafana.${ROOT_HOST}
      VIRTUAL_PORT: 3000
    depends_on:
      - prometheus 
      - acme-companion

  # Transmission container
  transmission:
    image: linuxserver/transmission:4.0.4@sha256:c8e397f2b39d0261b004d437fa4b4be48334c257c55e13b194001f0a212b5286
    container_name: transmission
    restart: always
    volumes:
      - "${DATA_DIR}/transmission/data:/config"
      - "${PLEX_MEDIA_DIR}/downloads:/downloads"
      - "${PLEX_MEDIA_DIR}/watch:/watch"
    hostname:
      transmission.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      TRANSMISSION_WEB_HOME: /config/combustion-release/
      USER: ${TRANSMISSION_USER}
      PASS: ${TRANSMISSION_PASSWORD}
      VIRTUAL_HOST: transmission.${ROOT_HOST}
      LETSENCRYPT_HOST: transmission.${ROOT_HOST}
      VIRTUAL_PORT: 9091
    depends_on:
      - acme-companion

  # Files Browser container
  files:
    image: filebrowser/filebrowser:v2.25.0@sha256:b06f6146754a44a492334947b0caa9ad93509ca1b04da8dacd3a76cdd4a2f471
    container_name: files
    restart: always
    volumes:
      - "${DATA_DIR}/filebrowser/data/filebrowser.db:/database/filebrowser.db"
      - "${PLEX_MEDIA_DIR}:/srv"
    command:
      - '--database'
      - '/database/filebrowser.db'
    hostname:
      files.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      VIRTUAL_HOST: files.${ROOT_HOST}
      LETSENCRYPT_HOST: files.${ROOT_HOST}
      VIRTUAL_PORT: 80
    depends_on:
      - acme-companion

  # Plex container
  plex:
    image: linuxserver/plex:1.32.6@sha256:785e1ddfdb444a960261805a85361186b2b21a552d80628ba9b1a8e4c1ce8d52
    container_name: plex
    restart: always
    volumes:
      - "${DATA_DIR}/plex:/config"
      - "${PLEX_MEDIA_DIR}:/media"
    hostname:
      plex.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM_TOKEN}
      VIRTUAL_HOST: plex.${ROOT_HOST}
      LETSENCRYPT_HOST: plex.${ROOT_HOST}
      VIRTUAL_PORT: 32400
    depends_on:
      - acme-companion

  # Calibre container
  calibre:
    image: linuxserver/calibre:6.26.0@sha256:c7042123778c501352bb3cb46cc211b736853f7e9c05399e9482f143449cd070
    container_name: calibre
    restart: always
    volumes:
      - "${DATA_DIR}/calibre:/config"
    hostname:
      calibre.${ROOT_HOST}
    ports:
      - 8080:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Sofia
      PASSWORD: ${CALIBRE_ADMIN_PWD}
      VIRTUAL_HOST: calibre.${ROOT_HOST}
      LETSENCRYPT_HOST: calibre.${ROOT_HOST}
      VIRTUAL_PORT: 8081
    depends_on:
      - acme-companion

  # Metube container
  metube:
    image: alexta69/metube:2023-08-19@sha256:2d2fd00ab4641984da3bf9aa4340aa1bfaf349fe4e030f2e7beb9703272cc2a2
    container_name: metube
    restart: always
    hostname:
      metube.${ROOT_HOST}
    volumes:
      - "${PLEX_MEDIA_DIR}/downloads:/downloads"
      - "${DATA_DIR}/metube/cookies:/cookies"
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Sofia
      VIRTUAL_HOST: metube.${ROOT_HOST}
      LETSENCRYPT_HOST: metube.${ROOT_HOST}
      VIRTUAL_PORT: 8081
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt"}'
    depends_on:
      - acme-companion

  # Postgres DB container
  postgresdb:
    image: postgres:15.4-alpine3.18@sha256:8bc3c893342c766481df5fde58fab6f1a1115b94eb56778126163305243e9709
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "${DATA_DIR}/postgresql:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}

  # Keycloak container
  keycloak:
    image: keycloak/keycloak:22.0.3@sha256:f00b8cd17decff83595da863daea9d0f853b3ab7fbf04e8820be3932eb81d2b2
    container_name: keycloak
    restart: always
    hostname: keycloak
    links:
      - postgresdb:postgresdb
    command:
    - 'start'
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresdb/${POSTGRES_DB_NAME}
      KC_DB_USERNAME: ${POSTGRES_DB_USER}
      KC_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: auth.${ROOT_HOST}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      LETSENCRYPT_HOST: auth.${ROOT_HOST}
      VIRTUAL_HOST: auth.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    healthcheck:
      test: cat /proc/net/tcp | grep '00000000:1F90 00000000:0000' || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 120s
    depends_on:
      - postgresdb
      - acme-companion

  # InvVal container
  invval:
    image: dzahariev/invval:2.0@sha256:984756d48e1d32e939a5b415b13cac012a6d1aa80c70fa8593d285c036892a89
    container_name: invval
    restart: always
    hostname:
      invval.${ROOT_HOST}
    environment:
      PUID: 1000
      PGID: 1000
      CLIENT_ID: ${INVVAL_CLIENT_ID}
      CLIENT_SECRET: ${INVVAL_CLIENT_SECRET} 
      REALM: ${INVVAL_REALM}
      KEYCLOAK_URL: https://auth.${ROOT_HOST} 
      BASE_URL: https://invval.${ROOT_HOST}
      TZ: Europe/Sofia
      VIRTUAL_HOST: invval.${ROOT_HOST}
      LETSENCRYPT_HOST: invval.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      keycloak:
        condition: service_healthy
