version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine@sha256:239c8485cf61ecb7500a95ae5202f15f641b13d02fa0b55c0173a7051197a228
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf

  acme-companion:
    image: nginxproxy/acme-companion:2.2@sha256:3f4f7339fa4606aa5ff1f9122bb5f6c8b673c738c60d3721a7526f25671bc873
    container_name: acme-companion
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/acme:/etc/acme.sh"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf
    environment: 
      DEFAULT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
    depends_on:
      - nginx-proxy

  grafana:
    image: nginxdemos/hello@sha256:ad10752170d6360abd7cc69981925aca006a784467003dfcb886e294af93c30e
    container_name: grafana
    restart: always
    environment: 
      VIRTUAL_HOST: grafana.${ROOT_HOST}
      LETSENCRYPT_HOST: grafana.${ROOT_HOST}
    depends_on:
      - acme-companion

  nextcloud:
    image: infrastructureascode/hello-world@sha256:1e584ae020df572d8f78ea7317cebfbc70cfa39d5fec0f254bb4666829c16759
    container_name: nextcloud
    restart: always
    environment: 
      VIRTUAL_HOST: nextcloud.${ROOT_HOST}
      LETSENCRYPT_HOST: nextcloud.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion
