version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine@sha256:58d20f216b3119f392705681a7c2562fe0279c6b48a9a1998b2c5ffc91e2a9f9
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf

  acme-companion:
    image: nginxproxy/acme-companion:2.2@sha256:9438ede8e4b8a1b8798c4af4683a04df5fdc0ea0d619fcd38598e4b85f362d02
    container_name: acme-companion
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DATA_DIR}/nginx/acme:/etc/acme.sh"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.conf:/etc/nginx/proxy.conf
    environment: 
      DEFAULT_EMAIL: ${DOMAIN_ADMIN_EMAIL}
    depends_on:
      - nginx-proxy

  grafana:
    image: nginxdemos/hello@sha256:dedfbe85183df66f3fdc99accf53e1b2171908dffd4d6556603ba4810b1fce6e
    container_name: grafana
    restart: always
    environment: 
      VIRTUAL_HOST: grafana.${ROOT_HOST}
      LETSENCRYPT_HOST: grafana.${ROOT_HOST}
    depends_on:
      - acme-companion

  nextcloud:
    image: infrastructureascode/hello-world@sha256:1e584ae020df572d8f78ea7317cebfbc70cfa39d5fec0f254bb4666829c16759
    container_name: nextcloud
    restart: always
    environment: 
      VIRTUAL_HOST: nextcloud.${ROOT_HOST}
      LETSENCRYPT_HOST: nextcloud.${ROOT_HOST}
      VIRTUAL_PORT: 8080
    depends_on:
      - acme-companion
